# Generated by Django 2.2 on 2019-11-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('catagory', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('badge', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
