# Generated by Django 2.2 on 2019-11-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191120_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
