# Generated by Django 3.0 on 2019-12-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191221_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('S', 'Shirt'), ('TS', 'T-Shirt'), ('FS', 'Full Sleeve T-Shirt'), ('H', 'Hoodie'), ('PJ', 'Panjabi'), ('PL', 'Polo')], max_length=2),
        ),
    ]
