# Generated by Django 3.0 on 2019-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191221_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('S', 'Shirt'), ('TS', 'T-Shirt'), ('FS', 'Full Sleeve T-Shirt'), ('H', 'Hoodie'), ('PJ', 'Panjabi'), ('PL', 'Polo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
