# Generated by Django 3.0 on 2019-12-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20191221_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('S', 'Shirt'), ('TS', 'T-Shirt'), ('FS', 'Full Sleeve T-Shirt'), ('H', 'Hoodie'), ('PJ', 'Panjabi'), ('PL', 'Polo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('N', 'Navy Blue'), ('R', 'Red'), ('M', 'Meroon')], max_length=20),
        ),
    ]
