# Generated by Django 3.0 on 2019-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20191221_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('NW', 'NEW'), ('BS', 'Best Seller')], max_length=20, null=True),
        ),
    ]
